ARG NODE_IMAGE=docker.m.daocloud.io/library/node:22-alpine
FROM ${NODE_IMAGE}
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5173
# Expose vite to 0.0.0.0 so it can be accessed from outside the container
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
