FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5173
# Expose vite to 0.0.0.0 so it can be accessed from outside the container
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
